"""Regenerates lib/domain/text/arabic_presentation_forms.g.dart.

Usage: python3 tool/gen_presentation_forms.py
"""
import unicodedata as u

rows = []
for rng in (range(0xFB50, 0xFE00), range(0xFE70, 0xFEFD)):
    for cp in rng:
        ch = chr(cp)
        try:
            u.name(ch)
        except ValueError:
            continue
        n = u.normalize('NFKC', ch)
        if n == ch:
            continue
        n = n.strip()  # isolated harakat forms decompose to " ً" etc.
        if n:
            rows.append((cp, n))


def esc(s):
    return ''.join('\\u{%X}' % ord(c) for c in s)


out = ['// GENERATED by tool/gen_presentation_forms.py from the Unicode Character',
       '// Database (NFKC decomposition of U+FB50-U+FDFF and U+FE70-U+FEFC).',
       '// Do not edit by hand.', '',
       '/// Maps each Arabic presentation-form code point to its base letters.',
       'const Map<int, String> arabicPresentationForms = {']
out += ["  0x%04X: '%s'," % (cp, esc(n)) for cp, n in rows]
out.append('};')
with open('lib/domain/text/arabic_presentation_forms.g.dart', 'w') as f:
    f.write('\n'.join(out) + '\n')
print(len(rows), 'entries')
